// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWIMEAp_4XNNj4Kt4x-JecJpAWGCc0Prw',
    appId: '1:590687863028:web:6c5c90ac43ba4ca0ef1ea1',
    messagingSenderId: '590687863028',
    projectId: 'advmobprog-firebase-7a5b5',
    authDomain: 'advmobprog-firebase-7a5b5.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-7a5b5.firebasestorage.app',
    measurementId: 'G-RCCJ7G3750',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS-T1ZQRGPYVQpw5o5SEWGg3cy1_AwjKc',
    appId: '1:590687863028:android:50f6a5024917fb42ef1ea1',
    messagingSenderId: '590687863028',
    projectId: 'advmobprog-firebase-7a5b5',
    storageBucket: 'advmobprog-firebase-7a5b5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl-wtb0_Vc65FDgKOIkAkBdOPtIpc0xXU',
    appId: '1:590687863028:ios:688e66dc67c5b77cef1ea1',
    messagingSenderId: '590687863028',
    projectId: 'advmobprog-firebase-7a5b5',
    storageBucket: 'advmobprog-firebase-7a5b5.firebasestorage.app',
    iosBundleId: 'com.example.ocrayAdvmobprog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl-wtb0_Vc65FDgKOIkAkBdOPtIpc0xXU',
    appId: '1:590687863028:ios:688e66dc67c5b77cef1ea1',
    messagingSenderId: '590687863028',
    projectId: 'advmobprog-firebase-7a5b5',
    storageBucket: 'advmobprog-firebase-7a5b5.firebasestorage.app',
    iosBundleId: 'com.example.ocrayAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWIMEAp_4XNNj4Kt4x-JecJpAWGCc0Prw',
    appId: '1:590687863028:web:0ece9c62736447e7ef1ea1',
    messagingSenderId: '590687863028',
    projectId: 'advmobprog-firebase-7a5b5',
    authDomain: 'advmobprog-firebase-7a5b5.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-7a5b5.firebasestorage.app',
    measurementId: 'G-ET5JNFP3NJ',
  );
}
